FROM python:3.9

WORKDIR /usr/src/app

RUN pip install flask
RUN pip install flask-cors
RUN pip install mysql
RUN pip install mysql-connector-python
RUN pip install flask_restful
RUN pip install sqlalchemy
RUN pip install python-dotenv
RUN pip install PyMySQL

WORKDIR /usr/src/app/backend
CMD python ./src/main.py